# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62b537551ed8bb821e45e7389b1a5d6258fe8c705f699915593631cbcb4b661c2a179ee33aca98deceb1892c08797a4e449669fcfe22c89b22eb88ee50e08f0f

test:
  secret_key_base: dda7be26d7c3716916004a085df0dfa3300a52f61ae667906a75045b605a8a1f34b8d02ff4dbf278970134159e2f0cddef6a64cf83d899125f278136ddbcdc5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
